### ISSUE TITLE
bfd_target_pdb_flavour missing

### ISSUE THREAD

**Issue by pdpdds** [lesderid/gdb-msvc#4]
../../bfd/targets.c:1806:10: error: ‘bfd_target_pdb_flavour’ undeclared (first use in this function); did you mean ‘bfd_target_pef_flavour’?
     case bfd_target_pdb_flavour: return "PDB";

**Comment by lesderid** [comment]
Oops, good catch, I must have edited a generated file by mistake. Fix coming soon.

**Comment by lesderid** [comment]
Fixed, thanks for letting me know!

You might want to subscribe to https://github.com/lesderid/gdb-msvc/issues/5 and/or https://github.com/lesderid/gdb-msvc/issues/6.
